### ISSUE TITLE
bug: Does not work in Glitch (maybe Glitch problems?)

### ISSUE THREAD

**Issue by RixInGithub** [lfortin/node-cgi-core#1] opened 2024-11-20 09:59 UTC
Hello!

Recently, I've been interested in making tiny CGI scripts for HTTPS. I started out by making a Glitch project, then I searched for CGI libraries for Node.js in npm. I found this library, and I thought it was easy to use.

I installed `node-cgi-core`, and coded up some beautiful code.
```js
http = require("http")
cgi = require("cgi-core")

c = {
  urlPath: "/cgi-bin/",
  filePath: "./cgi-bin/",
  debugOutput: true,
  indexExtension: "py",
  logRequests: true
}
hnd = cgi.createHandler(c)

http.createServer(async function(req, res) {
  var didHandle = await hnd(req, res)
  if (didHandle) return
  res.writeHead(500, {"Content-Type": "text/html"});
  res.end(`<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="data:;base64,=">
  </head>
  <body>
    <pre>CGI failed!</pre>
  </body>
</html>`)
}).listen(process.env.PORT || 3000, function() {
  console.log("Your app is running")
})
```

When I `GET` `/cgi-bin/env.js` it sends
```
500: Internal Server Error

Cannot read properties of undefined (reading 'F_OK')
```

<details>
<summary><code>env.js</code> source</summary>
Located at `./cgi-bin/env.js` (I made sure cwd is the place where `cgi-bin` is located.)

```js
process.stdout.write(`Content-Type: text/html

<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="data:;base64,=">
  </head>
  <body>
    <pre>${Object.entries(process.env).map(function(a){return a.join(": ")}).join("\n")}
`)
process.stdin.pipe(process.stdout)
process.stdout.write(`
</pre>
  </body>
</html>`)
```
</details>

Demo: https://zesty-autumn-skiff.glitch.me/cgi-bin/env.js
Repo: https://glitch.com/~zesty-autumn-skiff/

**Comment by lfortin** [comment] 2024-12-04 14:43
Thanks for opening this issue, @RixInGithub, and for using `cgi-core`!

The error you're encountering (`Cannot read properties of undefined (reading 'F_OK')`) suggests that the code is trying to access the `F_OK` property on an object that is undefined. This issue could be caused by an outdated or incompatible version of Node.js in your Glitch environment.

To resolve this, I recommend checking which version of Node.js you're running in your Glitch project. If you're using an older version, try updating it to a more recent one. You can do this by specifying a compatible Node.js version in your package.json file using the engines field:

```
"engines": {
  "node": ">=16.x"
}
```

This will ensure that your project uses a Node.js version that supports the necessary functionality. After making this change, try redeploying your project, and let me know if this resolves the issue.

**Comment by lfortin** [comment] 2024-12-16 03:31
Closing issue. Please re-open if further support needed.

**Closed as not planned** 2024-12-16 03:31 UTC
Labels: wontfix
